version: "3"
services:
  app:
    container_name: myapp
    build: ./docker/app
    restart: always
    volumes:
      - ./docker/app/:/usr/src/app
    # depends_on:
    #   - mydb


  db:
    container_name: mydb
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/mysql/initdb.d/:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d/:/etc/mysql/conf.d
