version: "3.8"

services:
  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
  
  server:
    build: ./server
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db